### ISSUE TITLE
Feature suggestion: Add support for text files

### ISSUE THREAD

**Issue by DonkeeeyKong** [OpenMediaVault-Plugin-Developers/openmediavault-scripts#1]
Thanks a lot for the plugin! Works great and I have already imported all of my scripts. 

I have scripts that use configuration files. I have been using plain text files for this (similar to e.g. /etc/passwd). It would be nice if there was an option to add or edit non-executable plain text files (*.txt or no filename extension at all) from the Web-GUI.

I know, I can also just use *.sh files to provide the configuration or edit them from CLI as before. If this feature is too difficult to implement I can easily use these options as well. 

Thanks for the great work!

**Comment by ryecoaaron** [comment]
That shouldn't be hard to add.  I need to make some other minor changes anyway.

**Comment by DonkeeeyKong** [comment]
Nice. Thank you! :)

**Comment by ryecoaaron** [comment]
7.0.2 is in the repo now.
