### ISSUE TITLE
When a textfile is modified outside of openmediavault the GUI doesn't recognize that and changes it back when opening.

### ISSUE THREAD

**Issue by DonkeeeyKong** [OpenMediaVault-Plugin-Developers/openmediavault-scripts#2]
Hey. Thanks a lot for the nice improvements. I found another bug though:

The description is pretty much in the title.

I have a script that reads content from a textfile and rearranges the content. The textfile is imported in the plugin.

When I do `cat textfile`  from the CLI after running the script, I see the updated content. When I open it from the plugin I see the old content and after doing that  `cat textfile`  shows the old content as well.

**Comment by DonkeeeyKong** [comment]
Or is there  command I can execute after modifying the file to sync the database with the new file content?

**Comment by ryecoaaron** [comment]
This is not a bug.  This is how OMV works.  The OMV database is the source of truth.  Changes from the command line will be overwritten.  I can look at adding a featuer to sync from the file (there is one in the compose plugin).

**Comment by ryecoaaron** [comment]
You can import changes from a script on the file system with the "Sync changes from file" option.

![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-scripts/assets/1914475/3f806d58-e9a3-45e4-80c9-d43535bc2c41)

**Comment by DonkeeeyKong** [comment]
Very nice. Thanks a lot! Is there any way to automate that or trigger that from a script?

**Comment by ryecoaaron** [comment]
That is really starting to get outside of the plugin.  You could make an rpc call but it would be a pain to find the UUID needed.  If you are doing everything outside of the plugin, what are you using the plugin for?

**Comment by DonkeeeyKong** [comment]
Okay. No problem. It works without that as well.

I use the plugin to edit and run several scripts and their config files. I find it very handy to be able to edit them from the browser instead of using SSH. 

I have one script that has a config file that in some cases is updated by the script. It's not a big problem if importing the changes is not automatable. A simple solution would have been handy but I am very happy with the situation as it is as well!

Thank you for all the useful plugins and the support!

**Comment by ryecoaaron** [comment]
I'll see if I can come up with something simple to run from the command line.

**Comment by ryecoaaron** [comment]
Here is a script.  I'm not going to include it with the plugin but I spent some time testing it.

https://github.com/ryecoaaron/scripts/blob/main/update_scripts_body_by_file.py

sudo ./update_scripts_body_by_file.py /srv/dev-disk-by-uuid-27f8af4d-9610-4ca6-be02-1d8f2bd54412/scripts/testSyncChanges.sh

**Comment by DonkeeeyKong** [comment]
Wow. Thank you so much! Works like a charm!
